
package plot;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JButton;

/**
 *
 * @author rick
 */
public class carteciano extends javax.swing.JPanel  {
    
    public  int c3,c2,c1,c; 
       double arreyX [] = new double[40];
        double arreyY [] = new double[40];
   ent_getTest Ent = new ent_getTest();
  
   JButton boton = new JButton("z");
   
  
   
    public carteciano() {
        initComponents();
        layout();
        this.setSize(400,400);
        
        boton.setSize(40,30);
        this.add(boton);
//        this.setLayout(new BoxLayout(this, BoxLayout.LINE_AXIS));
        
        
    }
    
    @Override
    public void paintComponent(Graphics g){
        g.setColor(Color.red);
        int px2 = this.getWidth()/2;
        int py2 = this.getHeight()/2;
        int px= this.getWidth();
        int py=this.getHeight();
        g.drawLine(px2,0, px2, py); //eje de las x
        g.drawLine(0,py2,px,py2 );        
        g.setColor(Color.black);
   for(int i=0; i<this.getWidth(); i=i+10){
            g.drawLine(i,py2-2,i,py2 + 2);
            g.drawLine(px2-2,i,px2+2,i);
        }  
  
   puntos();
  
        g.setColor(Color.blue);  
        double y[] = Ent.getarregloY();
        int puntoH = getpuntoHanchura();
        int puntoA = getpuntoAltura();
   for(int i=0; i<arreyY.length; i++){
        g.fillRect(((i-20)*10)+ puntoH, ((int)(-y[i]))+ puntoA, 2, 2);
        }
    }
    
//    public carteciano(Object ent){
//        
//        Ent = (ent_getTest) ent;
//        double Y[]= Ent.getarreglo();
//        System.arraycopy(Y, 0, y, 0, y.length);
//        repaint();
//    }
    
    public void puntos(){
                
//        c4*(Math.pow(i-20,4)) + c3*(Math.pow(i-20, 3)) +
// Plot p = new Plot();
        c3 = Plot.c3;
        c2 = Plot.c2;
        c1 = Plot.c1;
        c = Plot.c;
        
        for(int i=0; i<arreyX.length; i++){
            arreyY [i]= c3*(Math.pow(i-20, 3)) + c2*(Math.pow(i-20,2)) + c1 *(i-20) + c ;
            arreyX[i]=i-20;
            System.out.println(arreyY[i]);
    }
        Ent.setArregloY(arreyY);
    }
    
    public int getpuntoHanchura(){
        int puntoH = this.getWidth() /2;
        return puntoH;
    }
    public int getpuntoAltura(){
        int puntoA = this.getHeight() / 2;
        return puntoA;
    }
    


    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
